### ISSUE TITLE
Update links to Ansys help site to 25R1

### ISSUE THREAD

**Issue by ludovicsteinbach** [ansys/pygranta#116]
There are links to the Ansys help site in places, for example:
- https://bomanalytics.grantami.docs.pyansys.com/version/dev/api/sustainability/index.html
- https://recordlists.grantami.docs.pyansys.com/version/dev/user_guide/index.html

These all target the 24R1 version of the product documentation and need to be updated.

**Comment by Andy-Grigg** [comment]
We should probably write a script to do this, or maybe a github action to make the update if the pages can be resolved.
