### ISSUE TITLE
PyGranta packages general upkeep

### ISSUE THREAD

**Issue by ludovicsteinbach** [ansys/pygranta#26]
Ensure repositories are up to date with PyAnsys guidelines

- [x] Ensure pre-commit is configured
  - [ ] https://github.com/ansys/openapi-common/issues/547
  - [ ] https://github.com/ansys/grantami-bomanalytics-openapi/issues/127
  - [ ] https://github.com/ansys/grantami-serverapi-openapi/issues/173
  - [ ] https://github.com/ansys/grantami-bomanalytics/issues/484 (headers added, but hook failing to run in CI)
  - [x] https://github.com/ansys/grantami-recordlists/pull/205
- [x] Ensure compliance against [Project Structure](https://dev.docs.pyansys.com/packaging/structure.html)
- [ ] Configure PR labelling & auto-generated release notes
  - [x] https://github.com/ansys/openapi-common/pull/464
  - [ ] https://github.com/ansys/grantami-bomanalytics-openapi/issues/129
  - [ ] https://github.com/ansys/grantami-serverapi-openapi/issues/175
  - [x] https://github.com/ansys/grantami-bomanalytics/issues/486
  - [x] https://github.com/ansys/grantami-recordlists/pull/164
- [ ] Ensure CI uses ansys/actions wherever possible -
  - https://github.com/ansys/openapi-common/issues/549 
  - https://github.com/ansys/grantami-bomanalytics-openapi/issues/130
  - https://github.com/ansys/grantami-serverapi-openapi/issues/176
  - https://github.com/ansys/grantami-recordlists/issues/224 
  - https://github.com/ansys/grantami-bomanalytics/issues/487
- [x] PEP561 compliance
- [x] Use changelog action (Not 2024R2)
  - [ ] https://github.com/ansys/openapi-common/issues/548
  - [ ] https://github.com/ansys/grantami-bomanalytics-openapi/issues/128
  - [ ] https://github.com/ansys/grantami-serverapi-openapi/issues/174
  - [ ] https://github.com/ansys/grantami-bomanalytics/issues/490
  - [ ] https://github.com/ansys/grantami-recordlists/issues/227

**Comment by Andy-Grigg** [comment]
Closing this issue, see the [Project](https://github.com/orgs/ansys/projects/50) for an overview of the outstanding work.
