### ISSUE TITLE
Manage VM state more intelligently

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/pygranta#41]
We currently don't check to make sure that the test VM isn't in use before we turn it off. This was ok when we had 1 or 2 repositories, but it's not a sustainable solution.

Until we are able to use a containerized MI, we should either keep track of workflow instances using the machine, or a workflow should check if there are any other workflow instances (in any of the PyGranta repos) before shutting down the machine

**Comment by Andy-Grigg** [comment]
@ludovicsteinbach I think this is complete?

**Comment by ludovicsteinbach** [comment]
Yes, I'll close
